#!/usr/bin/env python3
"""Reference values for test/unit/test_math.cpp, as test/unit/math.data.

Hand-run, like the other five publishers in this directory; no build step calls
it. The oracle is the host's own libm through Python's math module, which is
within an ulp of correctly rounded for every function named here, so the budgets
in test_math.cpp absorb its error as well as ours.

  tools/mkmathdata.py > test/unit/math.data
"""

import math
import struct
import sys

# One entry per name: the function, and the arguments to sample it at. Chosen to
# cross every branch a kernel has -- the reduction thresholds, the polynomial
# switchover, either side of 1, and the subnormal and overflow ends.
SMALL = [0.0, 5e-324, 1e-300, 1e-30, 1e-8, 0.125, 0.5]
AROUND_ONE = [0.7, 0.9999999, 1.0, 1.0000001, 1.5, 2.0, 3.0]
LARGE = [10.0, 100.0, 708.0, 1e30, 1e300, 1.7976931348623157e308]
POSITIVE = SMALL + AROUND_ONE + LARGE
SIGNED = [-x for x in reversed(POSITIVE)] + POSITIVE
UNIT = [-1.0, -0.9999999, -0.5, -0.125, -1e-8, 0.0, 1e-8, 0.125, 0.5, 0.9999999, 1.0]
ANGLES = [
    0.0, 1e-8, 0.1, 0.5, 0.7853981633974483, 1.0, 1.5707963267948966, 2.0, 3.0,
    3.141592653589793, 4.0, 6.283185307179586, 10.0, 100.0, 1000.0, 1e6, 1e15,
]

ONE_ARG = [
    ("acos", math.acos, UNIT),
    ("acosh", math.acosh, [1.0, 1.0000001, 1.5, 2.0, 10.0, 1e8, 1e300]),
    ("asin", math.asin, UNIT),
    ("asinh", math.asinh, SIGNED),
    ("atan", math.atan, SIGNED),
    ("atanh", math.atanh, [x for x in UNIT if abs(x) < 1.0]),
    ("cbrt", math.cbrt if hasattr(math, "cbrt") else lambda x: math.copysign(abs(x) ** (1 / 3), x), SIGNED),
    ("cos", math.cos, [-x for x in reversed(ANGLES)] + ANGLES),
    ("cosh", math.cosh, [-710.0, -100.0, -1.0, 0.0, 1.0, 100.0, 709.0]),
    ("erf", math.erf, SIGNED),
    ("erfc", math.erfc, [-30.0, -1.0, 0.0, 0.5, 1.0, 2.0, 10.0, 26.0]),
    ("exp", math.exp, [-745.0, -709.0, -100.0, -1.0, 0.0, 0.5, 1.0, 100.0, 709.0]),
    ("exp2", math.exp2 if hasattr(math, "exp2") else lambda x: 2.0 ** x,
     [-1074.0, -100.0, -1.0, 0.0, 0.5, 1.0, 100.0, 1023.0]),
    ("expm1", math.expm1, [-745.0, -1.0, -1e-8, 0.0, 1e-8, 1.0, 709.0]),
    ("lgamma", math.lgamma, [0.5, 1.0, 1.5, 2.0, 3.0, 10.0, 100.0, 1e8]),
    ("log", math.log, POSITIVE[1:]),
    ("log10", math.log10, POSITIVE[1:]),
    ("log1p", math.log1p, [-0.9999999, -0.5, -1e-8, 0.0, 1e-8, 1.0, 1e300]),
    ("log2", math.log2, POSITIVE[1:]),
    ("sin", math.sin, [-x for x in reversed(ANGLES)] + ANGLES),
    ("sinh", math.sinh, [-710.0, -100.0, -1.0, -1e-8, 0.0, 1e-8, 1.0, 100.0, 709.0]),
    ("sqrt", math.sqrt, POSITIVE),
    ("tan", math.tan, [-x for x in reversed(ANGLES)] + ANGLES),
    ("tanh", math.tanh, SIGNED),
    ("tgamma", math.gamma, [-2.5, -0.5, 0.5, 1.0, 1.5, 2.0, 3.0, 10.0, 170.0]),
]

TWO_ARG = [
    ("atan2", math.atan2, [(y, x) for y in [-1e300, -1.0, -0.0, 0.0, 1.0, 1e300]
                           for x in [-1e300, -1.0, -0.0, 0.0, 1.0, 1e300]]),
    ("fmod", math.fmod, [(1e300, 3.0), (5.0, 3.0), (-5.0, 3.0), (5.0, -3.0),
                         (1.0, 1e-300), (0.5, 0.25), (1e10, 3.7)]),
    ("hypot", math.hypot, [(3.0, 4.0), (1e300, 1e300), (1e-300, 1e-300),
                           (0.0, 5.0), (1e300, 1.0), (-3.0, -4.0)]),
    ("pow", math.pow, [(2.0, 10.0), (10.0, 2.0), (2.0, 0.5), (1e300, 1.0),
                       (0.5, 100.0), (-2.0, 3.0), (-2.0, 4.0), (1.0000001, 1e7),
                       (2.0, -1074.0), (3.0, 0.3333333333333333)]),
    ("remainder", math.remainder, [(5.0, 3.0), (-5.0, 3.0), (5.5, 1.0),
                                   (1e300, 3.0), (4.5, 3.0)]),
]


def bits(x):
    return struct.unpack("<Q", struct.pack("<d", float(x)))[0]


def emit(out, name, rows):
    """Always three columns: x, y, want. y is 0 for a one-argument function."""
    out.write("static const MathCase %s_CASES[] = {\n" % name)
    for row in rows:
        out.write("    { %s },\n" % ", ".join("0x%016xull" % b for b in row))
    out.write("};\n\n")


def main():
    out = sys.stdout
    out.write("// Generated by tools/mkmathdata.py. Do not edit.\n")
    out.write("// x, y and the wanted result as raw f64 bits; y is 0 for a\n")
    out.write("// one-argument function. The oracle is the host's own libm.\n\n")

    for name, fn, args in ONE_ARG:
        rows = []
        for a in args:
            try:
                rows.append((bits(a), 0, bits(fn(a))))
            except (ValueError, OverflowError):
                continue
        emit(out, name, rows)

    for name, fn, pairs in TWO_ARG:
        rows = []
        for a, b in pairs:
            try:
                rows.append((bits(a), bits(b), bits(fn(a, b))))
            except (ValueError, OverflowError):
                continue
        emit(out, name, rows)


if __name__ == "__main__":
    main()
