#!/usr/bin/env python3
"""Reference streams for test/unit/test_zlib.cpp, as test/unit/zlib.data.

Hand-run, like the other publishers here; no build step calls it. The oracle is
the host's own zlib through Python's zlib module: for each case, the stream it
makes of one of the inputs below at one level, strategy, window and memory
level. braam::zlib is a translation of the same code, so it must make the same
stream, and the test compares them byte for byte by length and CRC-32 -- the
streams themselves would be most of the file.

The inputs are generated, not stored: the same LCG and word list are in the
test, and INPUT_SUMS pins what they made here, so the two cannot drift apart
unnoticed.

Two things are normalised. A gzip header's OS byte is the host's (19 on macOS),
and braam::zlib writes 3, Unix; it is set to 3 here before the CRC is taken.
And level 0 is recorded only for inputs that fit Python's first output block:
stored blocks are cut to the output room deflate is given, which Python grows
as it goes and the test does not.

zlib-ng makes other, equally valid, streams, so it is refused.

  tools/mkzlibdata.py > test/unit/zlib.data
"""

import sys
import zlib

if "ng" in zlib.ZLIB_RUNTIME_VERSION.lower():
    sys.exit(f"mkzlibdata: {zlib.ZLIB_RUNTIME_VERSION} is zlib-ng, not zlib")

WORDS = [b"the", b"of", b"and", b"deflate", b"window", b"a", b"stream", b"to",
         b"in", b"block", b"Huffman", b"is", b"that", b"match", b"code", b"for",
         b"length", b"distance", b"with", b"as", b"literal", b"tree", b"bits",
         b"on", b"by", b"hash", b"chain", b"lazy", b"it", b"be", b"zlib", b"at"]


class Lcg:
    def __init__(self, seed):
        self.x = seed

    def next(self):
        self.x = (self.x * 1103515245 + 12345) & 0xffffffff
        return (self.x >> 16) & 0x7fff


def text(seed, n):
    r = Lcg(seed)
    out = bytearray()
    while len(out) < n:
        out += WORDS[r.next() % len(WORDS)]
        k = r.next() % 16
        out += b"\n" if k == 0 else b", " if k == 1 else b" "
    return bytes(out[:n])


def noise(seed, n):
    r = Lcg(seed)
    return bytes(r.next() & 0xff for _ in range(n))


def runs(seed, n):
    r = Lcg(seed)
    out = bytearray()
    while len(out) < n:
        out += bytes([r.next() & 0xff]) * (1 + r.next() % 300)
    return bytes(out[:n])


def mixed(seed, n):
    out = bytearray()
    i = 0
    while len(out) < n:
        out += text(seed + i, 3000) if i % 2 == 0 else noise(seed + i, 1000)
        i += 1
    return bytes(out[:n])


# Index, as the test numbers them.
INPUTS = [
    b"",
    b"a",
    b"hello, hello, hello world\n",
    text(1, 12000),
    text(2, 150000),   # past twice the window: the slide
    noise(3, 20000),
    runs(4, 40000),
    mixed(5, 90000),
]

FIRST_BLOCK = 16384  # safely inside Python's first output block


def stream(data, level, strategy, wbits, memlevel):
    c = zlib.compressobj(level, zlib.DEFLATED, wbits, memlevel, strategy)
    out = bytearray(c.compress(data) + c.flush())
    if wbits > 15:
        out[9] = 3
    return bytes(out)


def cases():
    seen = set()

    def add(i, level, strategy, wbits, memlevel):
        if level == 0 and len(INPUTS[i]) > FIRST_BLOCK:
            return
        key = (i, level, strategy, wbits, memlevel)
        if key not in seen:
            seen.add(key)
            yield key

    for i in range(len(INPUTS)):
        for level in range(10):
            yield from add(i, level, 0, 15, 8)
    for i in (3, 4, 5, 6, 7):
        for strategy in (1, 2, 3, 4):
            for level in (1, 6, 9):
                yield from add(i, level, strategy, 15, 8)
    for i in (2, 3, 4, 7):
        for wbits in (8, 9, 10, 12, 14, -9, -12, -15, 25, 31):
            for level in (1, 6, 9):
                yield from add(i, level, 0, wbits, 8)
    for i in (3, 4, 7):
        for memlevel in (1, 2, 4, 7, 9):
            for level in (1, 6, 9):
                yield from add(i, level, 0, 15, memlevel)
    for i in (0, 1, 3):
        for wbits in (-15, 31):
            yield from add(i, 0, 0, wbits, 8)


def main():
    rows = []
    for (i, level, strategy, wbits, memlevel) in cases():
        s = stream(INPUTS[i], level, strategy, wbits, memlevel)
        rows.append(f"    {{ {i}, {level}, {strategy}, {wbits}, {memlevel}, "
                    f"{len(s)}, 0x{zlib.crc32(s):08x} }},")

    print("// Generated by tools/mkzlibdata.py. Do not edit.")
    print(f"// The host's zlib {zlib.ZLIB_RUNTIME_VERSION}: for each input, level,")
    print("// strategy, windowBits and memLevel, the length and CRC-32 of the")
    print("// stream it made. A gzip header's OS byte is taken as 3.")
    print()
    print("static const ZlibInputSum INPUT_SUMS[] = {")
    for data in INPUTS:
        print(f"    {{ {len(data)}, 0x{zlib.crc32(data):08x} }},")
    print("};")
    print()
    print("static const ZlibCase ZLIB_CASES[] = {")
    print("\n".join(rows))
    print("};")


if __name__ == "__main__":
    main()
